### ISSUE TITLE
Errors after connection on Firefox 48

### ISSUE THREAD

**Issue by ErnieAllen** [grs/rhea#14] opened 2016-08-16 16:08 UTC
I'm seeing errors that seem to only happen on Firefox 48 on Fedora 24.
Chrome on Fedora 24 works. Firefox version 42 on Fedora 23 works. 

What I expect to happen when using the attached html page is that when the connection is opened, the red "connecting..." text is replaced by the word "Connected" and then when I click on the button that a schema is returned.

I'm seeing two different behaviors :
Sometimes I get the connection_opened event but then I immediately get:
Error: Attach already received
rhea.js:1095:15
Then when I click the button to request a schema, I get:
TypeError: receiver.remote.attach is undefined
ff48fc24.html:65:17

However, sometimes I'll get a different behavior.  I'll immediately get:
Error: Invalid data offset, must be at least 2 was 0
rhea.js:737:15

and then after a few seconds I get:
Error: Close already received
rhea.js:469:15
[connection-1] disconnected
rhea.js:408:13
When that happens, I never get the connection_opened event and the "connecting..." text is never replaced.

Environment:
Fedora 24
Firefox 48
websockify for proxy (but also happens when I use nodejs for proxy)
I'm opening the reproducer file directly in a browser; no web server needed.
[ff48fc24.zip](https://github.com/grs/rhea/files/420725/ff48fc24.zip)

**Comment by ErnieAllen** [comment] 2016-08-18 16:39
More info: The errors are happening when I call either 
            connection.open_receiver or connection.open_sender

**Comment by ErnieAllen** [comment] 2016-08-18 17:56
For Windows 10 64bit:

    Firefox 48 - same errors
    Firefox 42 - no errors    
    Chrome - no errors

**Comment by ErnieAllen** [comment] 2016-08-18 18:37
This can also be reproduced using rhea/examples/websockets/client.html

**Comment by grs** [comment] 2016-08-18 18:53
On 18/08/16 19:37, Ernest Allen wrote:
> This can also be reproduced using rhea/examples/websockets/client.html

I'll get some time shortly to get hold of 48 and try to debug.

**Comment by ErnieAllen** [comment] 2016-09-26 20:27
This issue persists with the latest firefox 49.
To reproduce using rhea's example client.html on firefox 48 and 49 (both windows 10 and fedora 24):
- start qpid dispatch router and a proxy on 5673 (I'm using websockify for the proxy)
- cd examples/websockets
- firefox client.html
- open the firebug/developer console using F12
- in the popup input box enter "ws://localhost:5673" and click OK
- in the firefox console you will see         Error: Attach already received   line 1095

This does not happen using the same proxy in firefox 42 or chome.

**Comment by grs** [comment] 2016-10-04 08:51
I can't reproduce on firefox 49 using the client.html example and websockify (tried the javascript proxu first and that didn't cause any errors either). This was on fedora 23, but I don't think that should matter if the firefox and proxy version are the same. I tried with websockify versions 0.6.0 (latest in fedora23) and 0.8.0 (latest from pypi) and didn't see any error with either. What version are you using?

I can't unzip the attached file to try that, seems to be corrupted in some way?

**Comment by ErnieAllen** [comment] 2016-10-04 15:59
That is good news that you are not seeing the problem. 
I installed my websockify by:
    $ npm install websockify 
which installed python-websockify-0.8.0-1.fc24.noarch
Just for sanity sake, would you be willing to try the file attached to this post?
    - put the attached ff48fc24.txt in your rhea's examples/websockets/ directory
    - rename it to ff48fc24.html
    - $ firefox ff48fc24.html
    - open the developer console with F12 and view the 'console' tab
I'm seeing 'Error: Attach already received'

If you don't see the error and can click on the button and get a schema in response then I'll chalk it up to a problem on my machine and stop bugging you. :)

[ff48fc24.txt](https://github.com/grs/rhea/files/508886/ff48fc24.txt)

**Comment by grs** [comment] 2016-10-04 17:18
That file works for me. You see the error all the time?

**Comment by ErnieAllen** [comment] 2016-10-04 18:26
Yes, I see the same error every time. I suspect it is a problem with my proxy since I'm also seeing it when I connect from a Windows pc. I'll do some further research.

**Comment by grs** [comment] 2016-10-04 19:21
Can you try a pip installed proxy instead of the f24 package? Or the node proxy in proton/examples/javascript/messenger, just to verify that it is the proxy?

**Comment by grs** [comment] 2016-10-26 08:58
This seems to be based on the version of browserify used. 13.1.0 or later seems to work ok. For now I'll close this issue, if we need to dig deeper to allow older versions of browserify we can reopen.

**Closed by grs** 2016-10-26 08:58 UTC
